### ISSUE TITLE
Acceleration on common GPU

### ISSUE THREAD

**Issue by milliema** [AamirRaihan/SWAT#2]
Hi, thanks for the great work!
I know little about sparse computation, and I'm looking for methods that can speed up training process on common devices (e.g. NVIDIA GPU). I'm just wondering, if I adopt the SWAT method on common GPU devices (no special accelerator for sparse computation), will there be any benefits in terms of speed up?

**Comment by AamirRaihan** [comment]
It is difficult to speed up the training process on common GPUs because of the warp divergence and irregular memory access. It might be possible to get some speedup on NVIDIA's latest Ampere GPU. [Since the Ampere GPU's Tensor Cores support acceleration under structured sparsity](https://developer.nvidia.com/blog/exploiting-ampere-structured-sparsity-with-cusparselt).  However, we haven't tested it on Ampere GPU.

Thanks
